-- ============================================================
-- FOOD DELIVERY DATA ANALYSIS - SQL PROJECT
-- Author: N. Bharath Reddy
-- ============================================================

CREATE DATABASE food_delivery;
USE food_delivery;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(100),
    signup_date date
);

CREATE TABLE restaurants (
    restaurant_id INT PRIMARY KEY,
    restaurant_name VARCHAR(100),
    city VARCHAR(100),
    rating float
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    restaurant_id INT,
    order_date DATE,
    order_amount DECIMAL(10,2),
    payment_method VARCHAR(50),
    order_status VARCHAR(50),

    FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    FOREIGN KEY (restaurant_id)
        REFERENCES restaurants(restaurant_id)
);

select * from customers;
select * from restaurants;
select * from orders;

-- Q1: Which orders have been completed, along with the customer and restaurant involved?
select o.order_id, c.customer_name, r.restaurant_name, o.order_amount
from orders o join customers c
ON o.customer_id = c.customer_id
JOIN restaurants r
    ON o.restaurant_id = r.restaurant_id
WHERE o.order_status = 'Completed';

-- Q2: What is the total revenue generated by each restaurant?
select r.restaurant_name, sum(o.order_amount) as total_revenue
from orders o join restaurants r
on o.restaurant_id = r.restaurant_id
group by r.restaurant_name;

-- Q3: How many orders has each customer placed?
select c.customer_name, count(o.order_id) as total_orders
from orders o left join customers c
on o.customer_id= c.customer_id
group by c.customer_name;

-- Q4: What is the average order value by restaurant city?
select r.city, avg(o.order_amount) as avg_amnt
from orders o join restaurants r
on o.restaurant_id=r.restaurant_id
group by r.city;

-- Q5: How does each order classify when bucketed into Low / Medium / High value tiers?
select order_id, order_amount,
case
  when order_amount<200 then 'Low'
  when order_amount between 200 and 500 then 'Medium'
  else 'High'
end as category
from orders;

-- Q6: Which restaurants have an average order value above the platform-wide average?
select r.restaurant_name, avg(o.order_amount) as avg_amount
from orders o join restaurants r
on o.restaurant_id = r.restaurant_id
group by r.restaurant_name
having avg(o.order_amount) >(select avg(order_amount) from orders);

-- Q7: Which customers have signed up but never placed an order?
select c.customer_name
from customers c left join orders o
on c.customer_id=o.customer_id
where o.order_id is NULL;

-- Q8: Who are the top 5 customers by total lifetime spending?
select c.customer_name, sum(order_amount) as total_spending
from orders o join customers c
on o.customer_id=c.customer_id
group by c.customer_name
order by total_spending desc limit 5;

-- Q9: What is the most commonly used payment method?
select payment_method, count(*) as usage_count
from orders
group by payment_method
order by usage_count desc limit 1;

-- Q10: What is the daily revenue trend, along with a running (cumulative) total over time?
select order_date, sum(order_amount) as daily_revenue,
sum(sum(order_amount)) over (order by order_date) as running_total
from orders
group by order_date;

-- Q11: How do restaurants rank against each other by total revenue generated?
select r.restaurant_name, sum(o.order_amount) as daily_revenue,
 rank() over( order by SUM(o.order_amount) desc)
as ranking from orders o join restaurants r
 on o.restaurant_id = r.restaurant_id
group by r.restaurant_name;

-- Q12: What is the second-highest order amount placed on the platform?
select distinct order_amount
from orders
order by order_amount desc
limit 1 offset 1;

-- Q13: Which customers have placed more orders than the average customer?
select customer_id, count(order_id) as total_orders
from orders group by customer_id
having count(order_id)> (select avg(order_count) from
 ( select count(*) as order_count from orders group by customer_id) avg_table );

-- Q14: What are the top 3 restaurants by order volume within each city?
with restaurant_orders as
(
    select r.city, r.restaurant_name, count(o.order_id) as total_orders,
        rank() over
        (
            partition by r.city
            order by count(o.order_id) desc
        ) as ranking
    from restaurants r
    join orders o
        on r.restaurant_id = o.restaurant_id
    group by r.city, r.restaurant_name
)
select *
from restaurant_orders
where ranking <= 3;

-- Q15: What is the month-over-month revenue trend, comparing each month to the previous one?
select
    date_format(order_date, '%Y-%m') as month,
    sum(order_amount) as revenue,

    lag(sum(order_amount))
    over (
        order by date_format(order_date, '%Y-%m')
    ) as previous_month_revenue

from orders
group by date_format(order_date, '%Y-%m');


-- ============================================================
-- KEY INSIGHTS
-- Based on: 200 orders | 50 customers | 10 restaurants
-- Data range: Jan 2025 - May 2025 (May is partial, only 1 day of data)
-- ============================================================

-- 1) HIGH CANCELLATION RATE
--    94 of 200 orders (47%) are Cancelled; only 106 (53%) are Completed.
--    This is the single biggest red flag in the dataset - almost 1 in 2
--    orders never completes. Recommend investigating whether cancellations
--    cluster around a specific restaurant, payment method, or time window.

-- 2) REVENUE IS CONCENTRATED IN ONE RESTAURANT
--    Tandoori Nights generates 26,602 in revenue - 19.75% of total platform
--    revenue (134,756) from a single restaurant out of 10. It also has the
--    highest order volume of any restaurant in any city (34 orders in Delhi,
--    per Q14). Recommend treating it as a key partner and studying what
--    drives its performance (pricing, rating, delivery speed) to replicate
--    with mid-tier restaurants.

-- 3) ONLY 3 OF 10 RESTAURANTS BEAT THE PLATFORM AVERAGE ORDER VALUE
--    Platform-wide average order value is 673.78. Only Tandoori Nights
--    (782.41), BBQ Nation (744.44), and Spice Hub (735.92) exceed it -
--    meaning 70% of restaurants underperform on order value and may need
--    menu pricing or upsell support.

-- 4) CITY-LEVEL ORDER VALUE GAP
--    Mumbai has the highest average order value (735.92) while Hyderabad
--    has the lowest (610.67) - a 20.5% gap between the top and bottom city.
--    Worth checking whether this reflects restaurant mix, customer income
--    profile, or delivery radius differences.

-- 5) CUSTOMER BASE IS FULLY ACTIVE - NO DORMANT SIGNUPS
--    Q7 returns zero results: all 50 signed-up customers have placed at
--    least one order. Retention isn't the current problem area - order
--    completion (see insight #1) is.

-- 6) TOP 5 CUSTOMERS DRIVE ~19% OF REVENUE
--    The top 5 spenders (of 50 customers, 10%) contributed 25,847 combined -
--    19.18% of total revenue. Not extreme concentration, but still worth a
--    loyalty/retention push for this group, led by Nandini Rao (5,894).

-- 7) DEBIT CARD IS THE DOMINANT PAYMENT METHOD
--    Debit Card is used in 63 of 200 orders (31.5%), ahead of UPI (24%),
--    Cash (23%), and Credit Card (21.5%). Fairly balanced across methods,
--    but Debit Card should be the top priority for uptime/reliability since
--    it handles the largest single share of transactions.

-- 8) ORDER FREQUENCY: 38% OF CUSTOMERS ORDER MORE THAN AVERAGE
--    Average orders per customer is 4. 19 of 50 customers (38%) exceed this,
--    topping out at 8 orders (Nandini Rao). A healthy sign of repeat usage
--    across a meaningful share of the base, not just a handful of outliers.

-- 9) REVENUE PEAKED IN MARCH, THEN DECLINED
--    Monthly revenue: Jan 30,933 -> Feb 32,772 -> Mar 38,650 (peak) ->
--    Apr 31,111 -> May 1,290. March was the strongest month (+18% vs Jan),
--    but April dropped ~19.5% from the peak. Note: May's low figure reflects
--    only 1 day of data in this export, not a real decline - exclude it from
--    trend conclusions until a full month is available.
